### ISSUE TITLE
config request - disable number

### ISSUE THREAD

**Issue by rammoozz** [nozzle/nzTour#9]
Is there a config option for disabling numbers?

**Comment by lebolo** [comment]
In case others are interested, a quick workaround would be to add

``` css
#nzTour-step, #nzTour-length {
  display: none !important;
}
```

to your site.
